services:
  mongo:
    image: mongo:7
    container_name: geo-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: devpassword
    volumes:
      - geo-mongo-data:/data/db

volumes:
  geo-mongo-data: